# Generated by Django 2.2.26 on 2022-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220318_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
